---
- hosts: all
  remote_user: bb
  become: true  
  vars:
    ansible_become_password: "{{ user_sudo_pass }}"
  gather_facts: no  
  tasks:
  - name: Update apt cache
    apt:
      update_cache: yes

  - name: Upgrade all packages
    apt:
      upgrade: dist
      autoremove: yes
      update_cache: yes
  - name: Run do-release-upgrade
    command: do-release-upgrade
    register: release_upgrade_output
    failed_when: "'Checking for a new Ubuntu release' not in release_upgrade_output.stdout"
    changed_when: "'Checking for a new Ubuntu release' in release_upgrade_output.stdout"

  - name: Reboot the server (optional, if needed after the upgrade)
    reboot:
    when: release_upgrade_output.changed